export const EVENT_TYPE_OPTIONS = [
  'Wedding',
  'Engagement',
  'Reception',
  'Roka / Ring Ceremony',
  'Sangeet & Mehendi',
  'Haldi',
  'Bridal Shower',
  'Birthday',
  'Anniversary',
  'Baby Shower',
  'Naming Ceremony',
  'Housewarming',
  'Retirement Party',
  'Corporate Event',
  'Conference / Seminar',
  'Product Launch',
  'Private Party',
  'Cocktail Party',
  'Puja & Path',
  'Ramayan Path',
  'Akhand Path',
  'Sukhmani Sahib Path',
  'Kirtan / Jagran',
  'Nikah',
  'Walima',
  'Christian Wedding',
  'Baptism / Communion',
  'Festival Celebration',
  'Prayer Meeting',
  'Other',
] as const;

export type EventTypeOption = (typeof EVENT_TYPE_OPTIONS)[number];
